{
 "title": "Android app logs",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "App warnings",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time(({app=\"Android\"} |= \"\\\"level\\\":\\\"WARNING\\\"\")[$__range])"
    }
   ]
  },
  {
   "title": "CRASHES",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "count_over_time(({app=\"Android\"} |= \"\\\"level\\\":\\\"FATAL\\\"\")[$__range])"
    }
   ]
  },
  {
   "title": "ERRORS",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "count_over_time(({app=\"Android\"} |= \"\\\"level\\\":\\\"ERROR\\\"\")[$__range])"
    }
   ]
  }
 ]
}