{
 "title": "Resolver Success",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "container", "query": { "query": "label_values(container)" } }
  ]
 },
 "panels": [
  {
   "title": "Resolver Success",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(resolver_success{container=~\"$container\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Resolver Failure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(resolver_failure{container=\"$container\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Resolver Duration Sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "rate(resolver_duration_sum{container=\"$container\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Resolver Duration Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 17 },
   "targets": [
    {
     "expr": "rate(resolver_duration_count{container=\"$container\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Database Duration Sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "rate(database_duration_sum{container=\"$container\"}[$__interval])"
    }
   ]
  },
  {
   "title": "Database Duration Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 25 },
   "targets": [
    {
     "expr": "rate(database_duration_count{container=\"$container\"}[$__interval])"
    }
   ]
  }
 ]
}